#!/usr/bin/env ruby

require_relative 'gamescreen'
require_relative 'cardinal'
include Cardinal

screen = MainScreen.new
while true
  screen.lm.load_pieces
  input = screen.room.display
  screen.lm.move_piece("player", input)
end
